# Codecov configuration for pg_textsearch
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        # Only fail CI if coverage drops significantly
        threshold: 5%
        # Don't block PRs on coverage
        informational: true
    patch:
      default:
        # Coverage on changed lines
        threshold: 50%
        informational: true

# Ignore test files in coverage reports
ignore:
  - "test/**"
  - "benchmarks/**"

# Comment settings for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
