#!/bin/bash
#
# Segment WAL recovery test for pg_textsearch.
#
# Verifies that segment page writes produce WAL records so they
# survive a crash between checkpoints.
#
# Two-part test:
#
#   Part 1 (WAL coverage check):
#     Measure WAL bytes generated by an explicit spill.  Segment
#     pages are ~8kB each, so a 20+ page segment should generate
#     at least 100kB of WAL if pages are WAL-logged.  Without
#     GenericXLog the only WAL comes from the metapage linkage
#     (~100 bytes).
#
#   Part 2 (crash recovery):
#     Trigger auto-spill, SIGKILL, recover, query.  With WAL-
#     logged segment pages, the data survives.  Without, the
#     docid recovery path may mask the issue for simple cases,
#     but a second spill after recovery would read corrupt
#     segments during compaction.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_PORT=55442
TEST_DB=segment_wal_recovery_test
DATA_DIR="${SCRIPT_DIR}/../tmp_segment_wal_test"
LOGFILE="${DATA_DIR}/postgres.log"

PG_CONFIG="${PG_CONFIG:-pg_config}"
PGBINDIR="$($PG_CONFIG --bindir)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PASS_COUNT=0
FAIL_COUNT=0

log()   { echo -e "${GREEN}[$(date '+%H:%M:%S')] $1${NC}"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING: $1${NC}"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR: $1${NC}"; exit 1; }
info()  { echo -e "${BLUE}[$(date '+%H:%M:%S')] $1${NC}"; }

pass() {
    PASS_COUNT=$((PASS_COUNT + 1))
    log "PASS: $1"
}

fail() {
    FAIL_COUNT=$((FAIL_COUNT + 1))
    echo -e "${RED}[$(date '+%H:%M:%S')] FAIL: $1${NC}"
}

cleanup() {
    local exit_code=$?
    log "Cleaning up segment WAL test (exit code: $exit_code)..."
    jobs -p | xargs -r kill 2>/dev/null || true
    if [ -f "${DATA_DIR}/postmaster.pid" ]; then
        "${PGBINDIR}/pg_ctl" stop -D "${DATA_DIR}" -m fast \
            &>/dev/null ||
        "${PGBINDIR}/pg_ctl" stop -D "${DATA_DIR}" -m immediate \
            &>/dev/null || true
    fi
    rm -rf "${DATA_DIR}"
    exit $exit_code
}

trap cleanup EXIT INT TERM

run_sql() {
    "${PGBINDIR}/psql" -h "${DATA_DIR}" -p "${TEST_PORT}" \
        -d "${TEST_DB}" -c "$1" 2>&1
}

run_sql_quiet() {
    "${PGBINDIR}/psql" -h "${DATA_DIR}" -p "${TEST_PORT}" \
        -d "${TEST_DB}" -c "$1" >/dev/null 2>&1
}

run_sql_value() {
    "${PGBINDIR}/psql" -h "${DATA_DIR}" -p "${TEST_PORT}" \
        -d "${TEST_DB}" -tAc "$1" 2>/dev/null
}

simulate_crash() {
    log "Simulating crash (SIGKILL)..."
    local pid
    pid=$(head -1 "${DATA_DIR}/postmaster.pid")
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        kill -9 "$pid"
        sleep 2
        rm -f "${DATA_DIR}/postmaster.pid"
        log "Server killed (PID $pid)"
    else
        error "Could not find postmaster to kill"
    fi
}

restart_server() {
    log "Restarting server (recovery will run)..."
    "${PGBINDIR}/pg_ctl" start -D "${DATA_DIR}" \
        -l "${LOGFILE}" -w \
        || error "Server failed to restart after crash"
    run_sql_quiet "SELECT 1;" \
        || error "Cannot connect after restart"
    log "Server restarted"
}

# -------------------------------------------------------
# Setup
# -------------------------------------------------------

log "=========================================="
log "Segment WAL recovery test"
log "=========================================="

rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}"

"${PGBINDIR}/initdb" -D "${DATA_DIR}" \
    --auth-local=trust --auth-host=trust >/dev/null 2>&1

cat >> "${DATA_DIR}/postgresql.conf" << EOF
port = ${TEST_PORT}
max_connections = 20
shared_buffers = 128MB
unix_socket_directories = '${DATA_DIR}'
listen_addresses = 'localhost'
log_min_messages = warning
shared_preload_libraries = 'pg_textsearch'

# Tight memory limit so auto-spill triggers during inserts.
pg_textsearch.memory_limit = '4MB'
pg_textsearch.bulk_load_threshold = 0
pg_textsearch.memtable_spill_threshold = 0
pg_textsearch.segments_per_level = 2
EOF

"${PGBINDIR}/pg_ctl" start -D "${DATA_DIR}" -l "${LOGFILE}" -w \
    || error "Failed to start PostgreSQL"

"${PGBINDIR}/createdb" -h "${DATA_DIR}" -p "${TEST_PORT}" \
    "${TEST_DB}"
run_sql_quiet "CREATE EXTENSION pg_textsearch VERSION '1.0.0-dev';"

# -------------------------------------------------------
# Part 1: WAL coverage check
#
# Spill a memtable to a segment and measure how much WAL
# was generated.  Each segment page is ~8kB; a spill that
# creates N pages should generate at least N*8kB of WAL
# if the pages are WAL-logged via GenericXLog.
# -------------------------------------------------------

log "Part 1: WAL coverage check"

# Temporarily raise memory limit so data stays in memtable
# until we explicitly spill.
run_sql_quiet "ALTER SYSTEM SET pg_textsearch.memory_limit
                   = '256MB';"
run_sql_quiet "SELECT pg_reload_conf();"
sleep 0.2

run_sql_quiet "CREATE TABLE wal_check (
    id serial PRIMARY KEY, content text);"
run_sql_quiet "CREATE INDEX idx_wal_check ON wal_check
    USING bm25(content) WITH (text_config='english');"

# Load data into memtable (no spill — 256MB limit).
run_sql_quiet "INSERT INTO wal_check (content)
    SELECT 'walcheck_' || i || ' topic_' || (i % 50)
           || ' ' || repeat('pad_', 10)
    FROM generate_series(1, 3000) i;"

# Reset WAL stats, record LSN, spill, record LSN.
run_sql_quiet "SELECT pg_stat_reset_shared('wal');"
lsn_before=""
lsn_before=$(run_sql_value "SELECT pg_current_wal_insert_lsn();")

run_sql_quiet "SELECT bm25_spill_index('idx_wal_check');"

lsn_after=""
lsn_after=$(run_sql_value "SELECT pg_current_wal_insert_lsn();")
wal_bytes=""
wal_bytes=$(run_sql_value "SELECT wal_bytes FROM pg_stat_wal;")

# How many segment pages were written?
seg_pages=""
seg_pages=$(run_sql_value \
    "SELECT bm25_summarize_index('idx_wal_check');" \
    | grep -oE 'pages=[0-9]+' | head -1 \
    | grep -oE '[0-9]+' || echo 0)

info "Spill: $seg_pages segment pages, WAL: $wal_bytes bytes"
info "LSN: $lsn_before -> $lsn_after"

# Each page is 8192 bytes.  If WAL-logged, we expect at least
# seg_pages * 4096 bytes (conservative — deltas are smaller than
# full pages).  Without GenericXLog, WAL is < 1kB (just metapage).
min_expected_wal=$((seg_pages * 4096))

if [ "$wal_bytes" -ge "$min_expected_wal" ]; then
    pass "Part 1: spill generated ${wal_bytes} bytes WAL (>= ${min_expected_wal} for ${seg_pages} pages)"
else
    fail "Part 1: spill generated only ${wal_bytes} bytes WAL (expected >= ${min_expected_wal} for ${seg_pages} pages)"
fi

run_sql_quiet "DROP TABLE wal_check CASCADE;"

# Restore tight limit for Part 2.
run_sql_quiet "ALTER SYSTEM SET pg_textsearch.memory_limit
                   = '4MB';"
run_sql_quiet "SELECT pg_reload_conf();"
sleep 0.2

# -------------------------------------------------------
# Part 2: Crash recovery with spilled segments
#
# Trigger auto-spill, crash, recover,
# and verify a second spill + compaction cycle works (which
# requires reading the pre-crash segments).
# -------------------------------------------------------

log "Part 2: Crash recovery with segment reuse"

run_sql_quiet "CREATE TABLE recovery_test (
    id serial PRIMARY KEY, content text);"
run_sql_quiet "CREATE INDEX idx_recovery ON recovery_test
    USING bm25(content) WITH (text_config='english');"

# Insert enough to trigger auto-spill.
run_sql_quiet "INSERT INTO recovery_test (content)
    SELECT 'batch1_' || i || ' topic_' || (i % 40)
           || ' ' || repeat('pad_', 10)
    FROM generate_series(1, 3000) i;"

# Verify spill happened.
seg_before=""
seg_before=$(run_sql_value \
    "SELECT bm25_summarize_index('idx_recovery');" \
    | grep -oE 'Total: [0-9]+ segments' \
    | grep -oE '[0-9]+' || echo 0)
if [ "${seg_before:-0}" -eq 0 ]; then
    error "Part 2 setup: auto-spill did not occur"
fi
log "Pre-crash: $seg_before segments"

# Verify queryable.
pre_ct=""
pre_ct=$(run_sql_value \
    "SELECT count(*) FROM recovery_test
         WHERE content <@> 'batch1'::bm25query < 0;")
log "Pre-crash query: $pre_ct rows"

# Crash.
simulate_crash
restart_server

# Verify data survived recovery.
post_ct=""
post_ct=$(run_sql_value \
    "SELECT count(*) FROM recovery_test
         WHERE content <@> 'batch1'::bm25query < 0;" \
    || echo "QUERY_FAILED")

if [ "$post_ct" = "QUERY_FAILED" ]; then
    fail "Part 2a: query failed after recovery"
elif [ "$post_ct" -eq "$pre_ct" ]; then
    pass "Part 2a: query returns $post_ct rows after recovery (matches)"
else
    fail "Part 2a: post-crash $post_ct != pre-crash $pre_ct"
fi

# Insert a second batch to trigger another spill + compaction.
# With segments_per_level=2, two L0 segments trigger compaction,
# which reads the pre-crash segment.  If it's corrupt, this fails.
run_sql_quiet "INSERT INTO recovery_test (content)
    SELECT 'batch2_' || i || ' topic_' || (i % 40)
           || ' ' || repeat('pad_', 10)
    FROM generate_series(1, 3000) i;" \
    || true  # Don't abort on failure — we want to report it.

batch2_ct=""
batch2_ct=$(run_sql_value \
    "SELECT count(*) FROM recovery_test
         WHERE content <@> 'batch2'::bm25query < 0;" \
    || echo "QUERY_FAILED")

if [ "$batch2_ct" = "QUERY_FAILED" ]; then
    fail "Part 2b: query failed after post-recovery spill+compact"
elif [ "$batch2_ct" -eq 3000 ]; then
    pass "Part 2b: post-recovery spill+compact works ($batch2_ct rows)"
else
    fail "Part 2b: batch2 count=$batch2_ct (expected 3000)"
fi

# -------------------------------------------------------
# Summary
# -------------------------------------------------------

log "=========================================="
if [ "$FAIL_COUNT" -gt 0 ]; then
    error "$FAIL_COUNT test(s) FAILED, $PASS_COUNT passed"
else
    log "All tests passed ($PASS_COUNT assertions)"
fi
